### ISSUE TITLE
Library not loaded Error (0.7 Mac binary)

### ISSUE THREAD

**Issue by dvalentiate** [MitMaro/git-interactive-rebase-tool#100]
I get the following when I try to run `interactive-rebase-tool` either directly or using `git rebase -i origin/master`

> dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
>   Referenced from: /Users/david/bin/interactive-rebase-tool
>   Reason: image not found
> Abort trap: 6

I'm on a Mac and downloaded the executable directly from 
`https://github.com/MitMaro/git-interactive-rebase-tool/releases/download/0.7.0/macos-interactive-rebase-tool` and then used `mv ~/Downloads/macos-interactive-rebase-tool ~/bin/interactive-rebase-tool` and `chmod 755 ~/bin/interactive-rebase-tool`.

I've reverted to the [0.6](https://github.com/MitMaro/git-interactive-rebase-tool/releases/download/0.6.0/macos-git-interactive-rebase-tool) version which does work.

Also I really like this tool.

**Comment by MitMaro** [comment]
Thanks @dvalentiate ! OpenSSL was accidentally added as a dependency some time ago. This should be fixed in the upcoming release that I am hoping to get released soon.

If you use homebrew, you can also try to install the tool through homebrew using:

    brew install interactive-rebase-tool

That build should not have the dependency on openssl.

**Comment by MitMaro** [comment]
Version 1.0.0 has been fully released for MacOS and does not depend on OpenSSL.

Thanks for the report @dvalentiate !
