### ISSUE TITLE
When TODO list is empty, tool does not exit

### ISSUE THREAD

**Issue by StephenGregory** [MitMaro/git-interactive-rebase-tool#196]
I edited the TODO list manually, removed all commits, but saving it gives me:

"TODO list is empty
Press any key to continue"

Pressing a key opens the empty TODO list and the cycle repeats. Adding a "noop" is a workaround.

**Comment by MitMaro** [comment]
Thanks for the report, this is definitely a bug for an edge case.

**Comment by MitMaro** [comment]
Thanks @StephenGregory !

Turns out that this was by design and not a bug, but it was unexpected behavior.

My assumption when I wrote the original code was that an empty file would be because the external editor failed to save the file correctly. This missed the idea that someone would edit the file, remove all lines and then want to continue.

I've updated the external editor process to prompt when the external editing process returns an empty file. This allows a re-edit or to exit immediately.

![GIRT-Empty-Prmpt](https://user-images.githubusercontent.com/177427/71527810-96105380-28b7-11ea-9dfe-5537c3b3b8e3.png)
