### ISSUE TITLE
MacOS: ANSI color problems

### ISSUE THREAD

**Issue by dpplr** [MitMaro/git-interactive-rebase-tool#219]
Using version 1.2.0 i got following behaviour.

<img width="920" alt="before" src="https://user-images.githubusercontent.com/29912612/72336989-0f82b100-36c2-11ea-9da2-e0d905008854.png">
<img width="920" alt="mid" src="https://user-images.githubusercontent.com/29912612/72337001-15789200-36c2-11ea-8b72-4ad865a7dd4c.png">
<img width="920" alt="after" src="https://user-images.githubusercontent.com/29912612/72337019-19a4af80-36c2-11ea-990d-9984c7e42a9b.png">

As you can see color for i.e. bright-black seems to get changed but not reseted.

**Comment by MitMaro** [comment]
Thanks for the report @dpplr ! That's an odd one, as I didn't think it was possible to permanently change a terminals built-in colors. 

What terminal and OS are you using?

**Comment by dpplr** [comment]
Terminal: iterm2 Build 3.3.7
Shell: zsh 5.7.1
OS: macOS Catalina (10.15.2)

**Comment by MitMaro** [comment]
Thanks!

**Comment by MitMaro** [comment]
The good news is that I was able to reproduce the problem.

The bad news, I only have a slight idea on what is causing it.

**Comment by MitMaro** [comment]
It seems that ncurses on MacOS isn't properly resetting anything but the first 8 colors on shutdown. One solution is to not overwrite those colors on any system.

**Comment by MitMaro** [comment]
I have a solution to this problem, but it's going to take some time to implement.

For operating systems like MacOS, instead of defining custom colors, I need to match the provided color against the existing 256 colors defined in ANSI. I have this working locally for MacOS, but it breaks things in Linux and Windows.

I will need to add more collection of terminal information to determine which color system to use.

**Comment by MitMaro** [comment]
This has been tricky....

Turns out that full true color support was not added to Curses until version 6, but I am using bindings against an older version of Curses.

Eventually I would like to move to something like https://github.com/narfit66/ncursesw-rs which provides a better curses interface, but that has some complications for use in Windows.  I would need to interface with the Windows curses version directly (right now I use pancurses which handles the abstraction for me).

For now, I have written something that will try to match the RGB color provided against the closest ANSI color. This means dropping support for arbitrarily RGB colors for now, but it looks like support for that feature is limited to only a few terminals anyways.

I have learned more about colors in terminal emulators in the past year than I have in the last twenty using them...

Thanks again for the report!

**Comment by MitMaro** [comment]
@dpplr , I've released version 1.2.1 that should fix this issue. It's already on crates.io and I expect someone will get the Homebrew version bumped over this week.

Thanks again for the report! Apologizes for taking so long to get a fix released.

**Comment by dpplr** [comment]
@MitMaro  no worries, i am very happy that you managed to fix this issues. thx!
