### ISSUE TITLE
Create homebrew package.

### ISSUE THREAD

**Issue by DealPete** [MitMaro/git-interactive-rebase-tool#33]

**Comment by jay-hankins** [comment]
I started working on this, and submitted a formula PR here: https://github.com/Homebrew/homebrew-core/pull/34926

If anyone has ideas on the test function, I'd appreciate hearing them. The brew maintainers are reluctant to include the formula with the test as-is, although I argue the test I wrote is sufficient.

**Comment by MitMaro** [comment]
Wow! Thanks!

I think for the test, you could check that the file was correctly written. This tool doesn't really care about if the git rebase completes successfully, and just that the rebase-todo file was updated correctly.

**Comment by jay-hankins** [comment]
Yeah I understand where interactive-rebase-tool fits in the git flow 😉 Trying to convince the maintainers of homebrew that checking for a 0 status code and the presence of a rebase file is evidence enough that the tool is installed correctly 😇 

I'm not too familiar with git internals, basically anything in the `.git` folder. I think testing for a rebase-todo file to have some expected contents is doable, if you have recommendations for approaching that.

**Comment by MitMaro** [comment]
I'm going to move the discussion to this issue instead of doing a lot of back and forth on the homebrew PR.

There are already test files in https://github.com/MitMaro/git-interactive-rebase-tool/tree/master/test that could be used to test that the tool is working as expected. That would be a good starting place. The test would be something along the lines of:

```
      PTY.spawn("interactive-rebase-tool path/to/test/rebase-todo") do |_input, output, _pid|
        # send commands to the tool
        output.puts "p"
        output.puts "arrow-down" # not sure the character here
        output.puts "d"
        # etc..
        output.puts "W" # write file
      end
      # diff written file against expected output
```

I think that long term, having input provided through a file like vim does with the `-s` option would be a useful feature for both testing for homebrew and for testing of the tool in general.

**Comment by jay-hankins** [comment]
In the latest push (https://github.com/Homebrew/homebrew-core/commit/42cb5982173436a1aa620fdad2470c4e29e9c71b#diff-2a023a5392775b1eebd59a761897c24aR29) I compare the expected change to the todo file.

**Comment by MitMaro** [comment]
Homebrew/homebrew-core#34926 has been merged. Thanks @jay-hankins for putting in the effort!!
