### ISSUE TITLE
Entire screen flickers when rebasing a screen full of commits

### ISSUE THREAD

**Issue by SuperSandro2000** [MitMaro/git-interactive-rebase-tool#425]
When I rebase ~50 commits the entire screen flickers every time I move the cursor.

**Comment by MitMaro** [comment]
Thanks for the report! What terminal and OS are you using?

**Comment by SuperSandro2000** [comment]
bash version 5.0.17(1)-release in tmux over ssh in a Windows Terminal.

**Comment by MitMaro** [comment]
Thanks for the info. There isn't much that can be done here. Windows Terminal is fairly new and support for it is still not great. Hopefully, the team behind that project can improve the performance of the terminal. 

> I suspect that it redraws the entire screen every time I move my cursor instead of only the relevant parts.

This is tricky to do in a cross-platform way. Some terminals allow partial redraws, some do not. This may be something I decide to investigate and handle in the future.

**Comment by SuperSandro2000** [comment]
> Windows Terminal is fairly new and support for it is still not great.

Not really. It supports almost everything a terminal should support. For example I can scroll all day in htop without anything flickering.

> This is tricky to do in a cross-platform way. Some terminals allow partial redraws, some do not. This may be something I decide to investigate and handle in the future.

It should just work if you treat it like a normal Linux terminal. I am not using cmd I am using WSL in Windows Terminal which so far did support everything I threw it at like Konsole.

**Comment by nickolay** [comment]
I also see flickering in WezTerm on Windows 10. Per [their advice](https://github.com/wez/wezterm/issues/2443) I recorded the session and see that the "clear" command is flushed for some reason:
```
[44.986176,"o","\u001b[2J"]
[45.001392,"o","\u001b[4m\u001b[HGit Interactive Rebase Tool           
```

I'm not sure how to debug it, since the escape codes printed are very much different when running in VSCode's debugger.

Anyway there's a new feature in cross-term https://github.com/crossterm-rs/crossterm/pull/756, which should help here.
