### ISSUE TITLE
Please i want help

### ISSUE THREAD

**Issue by FayezElKenawy** [MitMaro/git-interactive-rebase-tool#50]
![screenshot_1](https://user-images.githubusercontent.com/25982832/42122299-4f49a77a-7c48-11e8-829c-c10dd9bf1c4b.png)

**Comment by MitMaro** [comment]
That doesn't seem to be using Visual Studio Code instead of this tool.

For Windows, once you [download the project](https://github.com/MitMaro/git-interactive-rebase-tool/releases/tag/20) you install the tool with:

```
git config --global core.editor "'C:/path/to/interactive-rebase-tool'"
```

Updating the path to correct location of the tool. Make sure that the `'` are not accidentally removed as the are important.

**Comment by MitMaro** [comment]
@FayezElKenawy I'm going to close the issue, as I don't think this is a bug with the tool If you feel there is a bug, please leave a comment and I will gladly reopen.
