### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by jgarte** [MitMaro/git-interactive-rebase-tool#573]
Do you happen to know what might cause these?

```
failures:
    external_editor::tests::activate_write_file_fail
    process::tests::error_write_todo
    tests::error_process
```

Some [more context](https://github.com/void-linux/void-packages/runs/4259542695?check_suite_focus=true).

**Comment by MitMaro** [comment]
I hate those particular tests because they are too fragile. I've been working to replace them with something a little more stable.

My guess, those tests depend on setting a file to be read only. If the OS/file system you are using doesn't support setting a file to read only, those tests will fail.

I also noticed in the test run you linked that `external_editor::tests::activate_write_file_fail` also failed, which requires writing a file. A small guess, is that the `test/fixtures/` directory doesn't have write permissions enabled for the user running the tests in GitHub actions.

**Comment by MitMaro** [comment]
Hey @jgarte , I'm going to close this issue, but if you have any other problems/questions feel free to comment/reopen.
