### ISSUE TITLE
Test Failure: tests::success Status(FileWriteError)

### ISSUE THREAD

**Issue by jgarte** [MitMaro/git-interactive-rebase-tool#586]
Hi, I get this test failure:

```
failures:

---- tests::success stdout ----
thread 'tests::success' panicked at '

Exit result does not match
==========
Expected:
Result(Abort, None)
Actual:
Result(None, Exit { Message(Error opening file: /tmp/guix-build-git-interactive-rebase-tool-2.1.0.drv-0/source/test/fixtures/simple/rebase-todo), Status(FileWriteError) })
==========
', src/testutil.rs:34:9


failures:
    tests::success

test result: FAILED. 1417 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.50s
```

Do you happen to know why this test fails? I'd just like to confirm that is because of write permissions. WDYT?

**Comment by jgarte** [comment]
My /tmp was not accessible in the container I was building from ;)

**Comment by MitMaro** [comment]
Yeah, I agree. It looks like a permissions issue. A number of the tests currently assume that the files/directories in `test/fixtures` are read/writable by the user. They also assume that files/directories can be set read only. I believe this means that the tests can't be run by root, since root users ignore permissions.
