### ISSUE TITLE
support new --update-refs feature

### ISSUE THREAD

**Issue by forivall** [MitMaro/git-interactive-rebase-tool#750]
Git added a new rebase feature: update-refs

https://github.blog/2022-10-03-highlights-from-git-2-38/#rebase-dependent-branches-with-update-refs

the line in a todo looks like
```
update-ref refs/heads/other-branch
```

I'll look at tackling this one too, in a separate PR.

**Comment by MitMaro** [comment]
That's a feature that I didn't know I wanted!

Adding support would be great!

I think initially, allowing it to be parsed (similar to how `exec` is currently parsed) would be enough. Since this would ensure that people using that option can continue to use the tool. I think then it can be followed up with adding support for the "edit" and "insert" lines functionality would be beneficial.

p.s. Thanks for bringing up these rebase changes/options. I haven't been as on top of the new changes to Git over the last while and have missed a lot.
