### ISSUE TITLE
Help (shift+`?`) keybinding broken on master

### ISSUE THREAD

**Issue by nickolay** [MitMaro/git-interactive-rebase-tool#837]
After 2c3ae588846912edf50992a0ad86ca792192fe79 pressing Shift+/ (i.e. "?") to invoke help doesn't work for me on Windows (in cmd.exe).

In https://github.com/MitMaro/git-interactive-rebase-tool/blob/bdf2f38066bc394584bc977f8ac1ad9d66aa1130/src/input/src/event_handler.rs#L57 the incoming `event` has the SHIFT modifier enabled, while the configured `self.key_bindings.help` does not.

**Comment by MitMaro** [comment]
Thanks for the report! This one is surprisingly tricky...

Sadly, Windows treats "Shift" + "Key" differently than other systems. Assuming a US QWERTY layout, when you press "Shift" + "/" for a "?", a "Shift" + "?" is provided on Windows. On other systems, it is normalized to just "?".

I thought I had handled this inconsistency a few times now, by trying to normalize the input, but I keep breaking different use cases. My [latest attempt](https://github.com/MitMaro/git-interactive-rebase-tool/blame/bdf2f38066bc394584bc977f8ac1ad9d66aa1130/src/input/src/key_event.rs) to address this, was to remove the "Shift" modifier on all ASCII uppercase letters. However, "?" isn't an upper case letter, so obviously that doesn't work.

I think a decent solution it to:

- expand the default keybindings, to include "shift" variants on Windows, this will address the default behaviour problems. This is tricky, since ideally the help wouldn't show these additional bindings.
- expand the normalization to handle some common keys from the most common keyboard layouts. While most keyboard layout change the position of various punctuation, they tend to keep the keys very similar. This will reduce confusion if folks decide to use custom keybindings.
- document that on Windows, if using a custom or lesser used keyboard layout, that some keybindings may require two bindings, one with shift and one without.

**Comment by nickolay** [comment]
What's wrong with [removing the SHIFT modifier from the incoming event](https://github.com/MitMaro/git-interactive-rebase-tool/commit/2c3ae588846912edf50992a0ad86ca792192fe79#diff-982c0adc60a745f75fa2fae42d5bc04e88476b8546105cf18eaeff2c8d2ee53dL29) before trying to find the matching keybinding? That's what you did before upgrading crossterm last year and it seemed to work well.

It looks like recognizing SHIFT modifier requires [support from the terminal](https://sw.kovidgoyal.net/kitty/keyboard-protocol/) as well as [the application](https://docs.rs/crossterm/latest/crossterm/event/struct.PushKeyboardEnhancementFlags.html), possibly not worth it for girt's use case?

**Comment by MitMaro** [comment]
> What's wrong with [removing the SHIFT modifier from the incoming event](https://github.com/MitMaro/git-interactive-rebase-tool/commit/2c3ae588846912edf50992a0ad86ca792192fe79#diff-982c0adc60a745f75fa2fae42d5bc04e88476b8546105cf18eaeff2c8d2ee53dL29) before trying to find the matching keybinding? That's what you did before upgrading crossterm last year and it seemed to work well.

The only real issue is a theoretical keybinding, where Shift + Char is wanted. That was my reasoning behind limiting it to ASCII uppercase characters. It's partially due to me not having or using non-US QWERTY keyboards, and being unsure how they register the shift modifier. But as you stated, getting Shift to be recognized is difficult across platform. You are probably correct, in that it's not worth it. Let me think on it.

**Comment by MitMaro** [comment]
Coming back to this issue, after a bit of a hiatus.

> You are probably correct, in that it's not worth it. Let me think on it.

You are correct, it's not worth the effort. I want to do a further refactor of how keybindings are handled, since it is currently fairly fragile (mostly around using `String`s for modifiers), which makes this kind of issue harder to fix.

However, I would like to get 2.3.0 released, and this is a blocker. To address the immediate issue, I am going to remove the Shift modifier from non-printable characters, and strip the shift modifier from any character events.

**Comment by nickolay** [comment]
Seems to work fine for me, thanks!
