### ISSUE TITLE
2.3.0 flickers when command names are changed

### ISSUE THREAD

**Issue by glensc** [MitMaro/git-interactive-rebase-tool#882]
changing `pick` to `rebase` would flicker screen and move everything to next column.

to reproduce pick a branch with at least two commits, press `r` for example.

https://github.com/MitMaro/git-interactive-rebase-tool/assets/199095/ae38204e-a6a6-4a3d-812e-85d9cfb62b20

**Comment by MitMaro** [comment]
Thanks for the report!

That was semi-intentional, as I made the width of the action dynamic with `update-ref` (or `fixup -C`), where before it was static. However, I think this should have a minimum to reduce the resize in the majority of cases.

I think the solution is to ensure that `maximum_action_width` in the follow has an allowed minimum of `6`, which was the old value. Then the resize will only happen on `update-ref` and other more "dynamic" actions.

https://github.com/MitMaro/git-interactive-rebase-tool/blob/033c6c86598b8df36004d314dd850aeb0cfeb300/src/core/src/modules/list/utils.rs#L271-L276

It's also possible to update the calculation of the width, but since the function could be used for other purposes in the future, I think it makes more sense to update in the "view build" instead.

https://github.com/MitMaro/git-interactive-rebase-tool/blob/033c6c86598b8df36004d314dd850aeb0cfeb300/src/core/src/modules/list/utils.rs#L199-L224
