### ISSUE TITLE
Debian package for older distros

### ISSUE THREAD

**Issue by yermulnik** [MitMaro/git-interactive-rebase-tool#89]
Would it be feasible to have exceptional package built for older Debian-based releases like Ubuntu 14.04 trusty? I've got a bunch of legacy setups where I'd like to use this tool but cannot upgrade to newer Ubuntu release =( If I got things right it's only about versions of dependencies not the tool itself.

Thanks in advance.

**Comment by MitMaro** [comment]
I'm thinking I should be able to use [packagecore](https://github.com/BytePackager/packagecore) to do releases based on Docker containers. This should make it possible to create a release for older versions of Debian-based distros.

**Comment by MitMaro** [comment]
The next release of the project will be releasing deb files for all Debian and Ubuntu versions that are currently in maintained. This will included Ubuntu version 14.04, as will be maintained until April, 2022.

Thanks for requesting this. I know it's taken a long time to get here and it's only because of the release of GitHub actions that I have been able to get this together.
