### ISSUE TITLE
Add NO_COLOR support

### ISSUE THREAD

**Issue by glensc** [MitMaro/git-interactive-rebase-tool#894]
It's an unfortunate rebase where I have only one commit, so I can't move arrow of of it to see what the commit is.
Also since this app seems to enabled mouse mode, I can not select the text (that usually will inverse the colors)
or copy the text to see somewhere elsewhere.

<img width="534" alt="image" src="https://github.com/MitMaro/git-interactive-rebase-tool/assets/199095/70290975-e46b-4814-aba1-12a43319798f">

But, there's NO_COLOR standard:
- https://no-color.org/
- https://www.gnu.org/software/gettext/libtextstyle/manual/html_node/The-NO_005fCOLOR-variable.html

please add NO_COLOR env variable support, so I could start my git rebase with that env variable set.

Command line option to git-interactive-rebase is difficult to use, because it's somewhere in config, need to find that config and it maybe even doesn't support command line options. <del>But I think make sense to keep the env variable in sync with command line options too.</del>

**Comment by MitMaro** [comment]
I had no idea that `NO_COLOR` was standardized, that's great!

This would be very, very easy to implement.

The color detection is all handled in one location: https://github.com/MitMaro/git-interactive-rebase-tool/blob/d7655157ff5d8e199291575b2ac0d1ac6267d69f/src/display/src/utils.rs#L7

It already reads a few environment variables to control the depth of color.

Having an early return of `ColorMode::TwoTone` would be really easy to implement.

> Command line option to git-interactive-rebase is difficult to use, because it's somewhere in config, need to find that config and it maybe even doesn't support command line options.

There aren't many command line arguments for the tool, mostly because most people never run it directly. There also isn't a argument for no color, and I don't think it's worth adding.

---

Semi-related, I know that the selected line background color doesn't work well in "non-dark" terminals. You can change that particular color, to make it compatible with your terminal. See [docs](https://github.com/MitMaro/git-interactive-rebase-tool/blob/master/readme/customization.md#colors).

**Comment by MitMaro** [comment]
This has been implemented in the main branch. Thanks for the report!
