### ISSUE TITLE
Commit information for renamed files in reverse order 

### ISSUE THREAD

**Issue by StephenGregory** [MitMaro/git-interactive-rebase-tool#925]
When pressing "c" to view commit information, I see:

```
renamed: foo/bar.java -> buzz/bar.java
```

However, bar.java moved from `buzz` to `foo`. 

`git log --stat 1234` displays:

```
{buzz => foo}/bar.java      | 0
```

Version: 2.4.0

**Comment by ccoVeille** [comment]
I'm using the tool for more than a year, if not more, and I had never noticed the `c` command.

You made my day @StephenGregory

**Comment by MitMaro** [comment]
Thanks for the bug report @StephenGregory !

Looks like the mistake is here https://github.com/MitMaro/git-interactive-rebase-tool/blob/2d458aa97cb9b2ba9cc59a5f11b6ba7a9c931f5b/src/modules/show_commit/util.rs#L83

I would like to say that was due to some refactoring I did with the recent release, but it's existed for around 5 years. 😅

Thankfully it should be an easy fix, and I can push out a release shortly after.

**Comment by ccoVeille** [comment]
Do we win something ?  like the one who find the oldest bug gets a  laptop sticker?

**Comment by MitMaro** [comment]
Interestingly enough, I'm pretty sure @StephenGregory has a sticker on a laptop that I probably gave him, though that was years ago.

@ccoVeille , if you were geographically closer, I would gladly provide a sticker for a community group I help run. :D

**Comment by ccoVeille** [comment]
France here, how far are you?
